version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
    ports:
      - "9042:9042"
    networks:
      - cassandra-net

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
    networks:
      - cassandra-net

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2,cassandra3"
    networks:
      - cassandra-net

  myapp:
    build: src/main/resources
    container_name: my-spring-boot-app
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
    environment:
      SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra1,cassandra2,cassandra3
      SPRING_DATA_CASSANDRA_PORT: 9042
    ports:
      - "8082:8082"
    networks:
      - cassandra-net

networks:
  cassandra-net: